#!/usr/bin/env bash 

set -e 

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$script_dir/../commons.sh"

# Parse command-line options, standardized options for all clients
parse_options "$@"

# Define default values
DEFAULT_DATADIR="$HOME/.ethereum"
DEFAULT_AUTHRPC_ADDR="localhost"
DEFAULT_AUTHRPC_PORT=8551
DEFAULT_AUTHRPC_VHOSTS="localhost"
DEFAULT_HTTP=false
DEFAULT_HTTP_ADDR="localhost"
DEFAULT_HTTP_PORT=8545
DEFAULT_HTTP_VHOSTS="localhost"
DEFAULT_WS=false
DEFAULT_WS_ADDR="localhost"
DEFAULT_WS_PORT=8546
DEFAULT_GRAPHQL=false
DEFAULT_GRAPHQL_VHOSTS="localhost"
DEFAULT_VERBOSITY=3
DEFAULT_ALLOW_INSECURE_UNLOCK=false
DEFAULT_LIGHTKDF=false
DEFAULT_PCSCDPATH="/run/pcscd/pcscd.comm"
DEFAULT_USB=false
DEFAULT_CACHE_TRIE_REJOURNAL="0s"
DEFAULT_LIGHT_EGRESS=0
DEFAULT_LIGHT_INGRESS=0
DEFAULT_LIGHT_MAXPEERS=100
DEFAULT_LIGHT_NOPRUNING=false
DEFAULT_LIGHT_NOSYNCSERVE=false
DEFAULT_LIGHT_SERVE=0
DEFAULT_LOG_DEBUG=false
DEFAULT_METRICS_EXPENSIVE=false
DEFAULT_MINE=false
DEFAULT_MINER_NEWPAYLOAD_TIMEOUT="2s"
DEFAULT_NOUSB=false
DEFAULT_TXLOOKUPLIMIT=2350000
DEFAULT_V5DISC=false
DEFAULT_RPC_ALLOW_UNPROTECTED_TXS=false
DEFAULT_RPC_BATCH_REQUEST_LIMIT=1000
DEFAULT_RPC_BATCH_RESPONSE_MAX_SIZE=25000000
DEFAULT_RPC_ENABLEDEPRECATEDPERSONAL=false
DEFAULT_RPC_EVMTIMEOUT="5s"
DEFAULT_RPC_GASCAP=50000000
DEFAULT_RPC_TXFEECAP=1
DEFAULT_BEACON_GENESIS_TIME=0
DEFAULT_BEACON_THRESHOLD=342
DEFAULT_DEV=false
DEFAULT_DEV_GASLIMIT=11500000
DEFAULT_DEV_PERIOD=0
DEFAULT_BLOOMFILTER_SIZE=2048
DEFAULT_EXITWHENSYNCED=false
DEFAULT_GOERLI=false
DEFAULT_HOLESKY=false
DEFAULT_NETWORKID=0
DEFAULT_OVERRIDE_CANCUN=0
DEFAULT_OVERRIDE_VERKLE=0
DEFAULT_SEPOLIA=false
DEFAULT_SNAPSHOT=true
DEFAULT_GPO_BLOCKS=20
DEFAULT_GPO_IGNOREPRICE=2
DEFAULT_GPO_MAXPRICE=500000000000
DEFAULT_GPO_PERCENTILE=60
DEFAULT_LOG_COMPRESS=false
DEFAULT_LOG_MAXAGE=30
DEFAULT_LOG_MAXBACKUPS=10
DEFAULT_LOG_MAXSIZE=100
DEFAULT_LOG_ROTATE=false
DEFAULT_NOCOMPACTION=false
DEFAULT_PPROF=false
DEFAULT_PPROF_ADDR="127.0.0.1"
DEFAULT_PPROF_BLOCKPROFILERATE=0
DEFAULT_PPROF_MEMPROFILERATE=524288
DEFAULT_PPROF_PORT=6060
DEFAULT_VERBOSITY=3
DEFAULT_METRICS=false
DEFAULT_METRICS_INFLUXDB=false
DEFAULT_METRICS_INFLUXDB_BUCKET="geth"
DEFAULT_METRICS_INFLUXDB_DATABASE="geth"
DEFAULT_METRICS_INFLUXDB_ENDPOINT="http://localhost:8086"
DEFAULT_METRICS_INFLUXDB_ORGANIZATION="geth"
DEFAULT_METRICS_INFLUXDB_PASSWORD="test"
DEFAULT_METRICS_INFLUXDB_TAGS="host=localhost"
DEFAULT_METRICS_INFLUXDB_TOKEN="test"
DEFAULT_METRICS_INFLUXDB_USERNAME="test"
DEFAULT_METRICS_INFLUXDBV2=false
DEFAULT_METRICS_PORT=6060
DEFAULT_MINER_GASLIMIT=30000000
DEFAULT_MINER_GASPRICE=1000000000
DEFAULT_MINER_RECOMMIT="2s"
DEFAULT_DISCOVERY_PORT=30303
DEFAULT_DISCOVERY_V4=true
DEFAULT_DISCOVERY_V5=false
DEFAULT_MAXPEERS=50
DEFAULT_MAXPENDPEERS=0
DEFAULT_NAT="any"
DEFAULT_NODISCOVER=false
DEFAULT_PORT=30303
DEFAULT_CACHE=1024
DEFAULT_CACHE_BLOCKLOGS=32
DEFAULT_CACHE_DATABASE=50
DEFAULT_CACHE_GC=25
DEFAULT_CACHE_NOPREFETCH=false
DEFAULT_CACHE_PREIMAGES=false
DEFAULT_CACHE_SNAPSHOT=10
DEFAULT_CACHE_TRIE=15
DEFAULT_CRYPTO_KZG="gokzg"
DEFAULT_FDLIMIT=0
DEFAULT_GCMODE="full"
DEFAULT_HISTORY_STATE=90000
DEFAULT_HISTORY_TRANSACTIONS=2350000
DEFAULT_SYNCMODE="snap"
DEFAULT_BLOBPOOL_DATACAP=2684354560
DEFAULT_BLOBPOOL_DATADIR="blobpool"
DEFAULT_BLOBPOOL_PRICEBUMP=100
DEFAULT_TXPOOL_ACCOUNTQUEUE=64
DEFAULT_TXPOOL_ACCOUNTSLOTS=16
DEFAULT_TXPOOL_GLOBALQUEUE=1024
DEFAULT_TXPOOL_GLOBALSLOTS=5120
DEFAULT_TXPOOL_JOURNAL="transactions.rlp"
DEFAULT_TXPOOL_LIFETIME="3h0m0s"
DEFAULT_TXPOOL_NOLOCALS=false
DEFAULT_TXPOOL_PRICEBUMP=10
DEFAULT_TXPOOL_PRICELIMIT=1
DEFAULT_TXPOOL_REJOURNAL="1h0m0s"
DEFAULT_VMDEBUG=false

# Start the Geth node using environment variables
geth \
 --mainnet \
 --datadir "${DATADIR:-$DEFAULT_DATADIR}" \
 --authrpc.addr "${AUTHRPC_ADDR:-$DEFAULT_AUTHRPC_ADDR}" \
 --authrpc.port "${AUTHRPC_PORT:-$DEFAULT_AUTHRPC_PORT}" \
 --authrpc.vhosts "${AUTHRPC_VHOSTS:-$DEFAULT_AUTHRPC_VHOSTS}" \
 --authrpc.jwtsecret "${AUTHRPC_JWTSECRET:-$script_dir/secrets.jwt}" \
 --http "${HTTP:-$DEFAULT_HTTP}" \
 --http.api "${HTTP_API}" \
 --http.addr "${HTTP_ADDR:-$DEFAULT_HTTP_ADDR}" \
 --http.port "${HTTP_PORT:-$DEFAULT_HTTP_PORT}" \
 --http.corsdomain "${HTTP_CORSDOMAIN}" \
 --http.vhosts "${HTTP_VHOSTS:-$DEFAULT_HTTP_VHOSTS}" \
 --ws "${WS:-$DEFAULT_WS}" \
 --ws.api "${WS_API}" \
 --ws.addr "${WS_ADDR:-$DEFAULT_WS_ADDR}" \
 --ws.port "${WS_PORT:-$DEFAULT_WS_PORT}" \
 --ws.origins "${WS_ORIGINS}" \
 --graphql "${GRAPHQL:-$DEFAULT_GRAPHQL}" \
 --graphql.vhosts "${GRAPHQL_VHOSTS:-$DEFAULT_GRAPHQL_VHOSTS}" \
 --graphql.corsdomain "${GRAPHQL_CORSDOMAIN}" \
 --exec "${EXEC}" \
 --verbosity "${VERBOSITY:-$DEFAULT_VERBOSITY}" \
 --allow-insecure-unlock "${ALLOW_INSECURE_UNLOCK:-$DEFAULT_ALLOW_INSECURE_UNLOCK}" \
 --keystore "${KEYSTORE}" \
 --lightkdf "${LIGHTKDF:-$DEFAULT_LIGHTKDF}" \
 --password "${PASSWORD}" \
 --pcscdpath "${PCSCDPATH:-$DEFAULT_PCSCDPATH}" \
 --signer "${SIGNER}" \
 --unlock "${UNLOCK}" \
 --usb "${USB:-$DEFAULT_USB}" \
 --cache.trie.journal "${CACHE_TRIE_JOURNAL}" \
 --cache.trie.rejournal "${CACHE_TRIE_REJOURNAL:-$DEFAULT_CACHE_TRIE_REJOURNAL}" \
 --light.egress "${LIGHT_EGRESS:-$DEFAULT_LIGHT_EGRESS}" \
 --light.ingress "${LIGHT_INGRESS:-$DEFAULT_LIGHT_INGRESS}" \
 --light.maxpeers "${LIGHT_MAXPEERS:-$DEFAULT_LIGHT_MAXPEERS}" \
 --light.nopruning "${LIGHT_NOPRUNING:-$DEFAULT_LIGHT_NOPRUNING}" \
 --light.nosyncserve "${LIGHT_NOSYNCSERVE:-$DEFAULT_LIGHT_NOSYNCSERVE}" \
 --light.serve "${LIGHT_SERVE:-$DEFAULT_LIGHT_SERVE}" \
 --log.backtrace "${LOG_BACKTRACE}" \
 --log.debug "${LOG_DEBUG:-$DEFAULT_LOG_DEBUG}" \
 --metrics.expensive "${METRICS_EXPENSIVE:-$DEFAULT_METRICS_EXPENSIVE}" \
 --mine "${MINE:-$DEFAULT_MINE}" \
 --miner.etherbase "${MINER_ETHERBASE}" \
 --miner.newpayload-timeout "${MINER_NEWPAYLOAD_TIMEOUT:-$DEFAULT_MINER_NEWPAYLOAD_TIMEOUT}" \
 --nousb "${NOUSB:-$DEFAULT_NOUSB}" \
 --txlookuplimit "${TXLOOKUPLIMIT:-$DEFAULT_TXLOOKUPLIMIT}" \
 --v5disc "${V5DISC:-$DEFAULT_V5DISC}" \
 --whitelist "${WHITELIST}" \
 --authrpc.jwtsecret "${AUTHRPC_JWTSECRET}" \
 --header "${HEADER}" \
 --rpc.allow-unprotected-txs "${RPC_ALLOW_UNPROTECTED_TXS:-$DEFAULT_RPC_ALLOW_UNPROTECTED_TXS}" \
 --rpc.batch-request-limit "${RPC_BATCH_REQUEST_LIMIT:-$DEFAULT_RPC_BATCH_REQUEST_LIMIT}" \
 --rpc.batch-response-max-size "${RPC_BATCH_RESPONSE_MAX_SIZE:-$DEFAULT_RPC_BATCH_RESPONSE_MAX_SIZE}" \
 --rpc.enabledeprecatedpersonal "${RPC_ENABLEDEPRECATEDPERSONAL:-$DEFAULT_RPC_ENABLEDEPRECATEDPERSONAL}" \
 --rpc.evmtimeout "${RPC_EVMTIMEOUT:-$DEFAULT_RPC_EVMTIMEOUT}" \
 --rpc.gascap "${RPC_GASCAP:-$DEFAULT_RPC_GASCAP}" \
 --rpc.txfeecap "${RPC_TXFEECAP:-$DEFAULT_RPC_TXFEECAP}" \
 --beacon.api "${BEACON_API}" \
 --beacon.api.header "${BEACON_API_HEADER}" \
 --beacon.checkpoint "${BEACON_CHECKPOINT}" \
 --beacon.config "${BEACON_CONFIG}" \
 --beacon.genesis.gvroot "${BEACON_GENESIS_GVROOT}" \
 --beacon.genesis.time "${BEACON_GENESIS_TIME:-$DEFAULT_BEACON_GENESIS_TIME}" \
 --beacon.nofilter "${BEACON_NOFILTER:-$DEFAULT_BEACON_NOFILTER}" \
 --beacon.threshold "${BEACON_THRESHOLD:-$DEFAULT_BEACON_THRESHOLD}" \
 --dev "${DEV:-$DEFAULT_DEV}" \
 --dev.gaslimit "${DEV_GASLIMIT:-$DEFAULT_DEV_GASLIMIT}" \
 --dev.period "${DEV_PERIOD:-$DEFAULT_DEV_PERIOD}" \
 --bloomfilter.size "${BLOOMFILTER_SIZE:-$DEFAULT_BLOOMFILTER_SIZE}" \
 --datadir.ancient "${DATADIR_ANCIENT}" \
 --datadir.minfreedisk "${DATADIR_MINFREEDISK}" \
 --db.engine "${DB_ENGINE}" \
 --eth.requiredblocks "${ETH_REQUIREDBLOCKS}" \
 --exitwhensynced "${EXITWHENSYNCED:-$DEFAULT_EXITWHENSYNCED}" \
 --goerli "${GOERLI:-$DEFAULT_GOERLI}" \
 --holesky "${HOLESKY:-$DEFAULT_HOLESKY}" \
 --networkid "${NETWORKID:-$DEFAULT_NETWORKID}" \
 --override.cancun "${OVERRIDE_CANCUN:-$DEFAULT_OVERRIDE_CANCUN}" \
 --override.verkle "${OVERRIDE_VERKLE:-$DEFAULT_OVERRIDE_VERKLE}" \
 --sepolia "${SEPOLIA:-$DEFAULT_SEPOLIA}" \
 --snapshot "${SNAPSHOT:-$DEFAULT_SNAPSHOT}" \
 --gpo.blocks "${GPO_BLOCKS:-$DEFAULT_GPO_BLOCKS}" \
 --gpo.ignoreprice "${GPO_IGNOREPRICE:-$DEFAULT_GPO_IGNOREPRICE}" \
 --gpo.maxprice "${GPO_MAXPRICE:-$DEFAULT_GPO_MAXPRICE}" \
 --gpo.percentile "${GPO_PERCENTILE:-$DEFAULT_GPO_PERCENTILE}" \
 --log.compress "${LOG_COMPRESS:-$DEFAULT_LOG_COMPRESS}" \
 --log.file "${LOG_FILE}" \
 --log.format "${LOG_FORMAT}" \
 --log.maxage "${LOG_MAXAGE:-$DEFAULT_LOG_MAXAGE}" \
 --log.maxbackups "${LOG_MAXBACKUPS:-$DEFAULT_LOG_MAXBACKUPS}" \
 --log.maxsize "${LOG_MAXSIZE:-$DEFAULT_LOG_MAXSIZE}" \
 --log.rotate "${LOG_ROTATE:-$DEFAULT_LOG_ROTATE}" \
 --log.vmodule "${LOG_VMODULE}" \
 --nocompaction "${NOCOMPACTION:-$DEFAULT_NOCOMPACTION}" \
 --pprof "${PPROF:-$DEFAULT_PPROF}" \
 --pprof.addr "${PPROF_ADDR:-$DEFAULT_PPROF_ADDR}" \
 --pprof.blockprofilerate "${PPROF_BLOCKPROFILERATE:-$DEFAULT_PPROF_BLOCKPROFILERATE}" \
 --pprof.cpuprofile "${PPROF_CPUPROFILE}" \
 --pprof.memprofilerate "${PPROF_MEMPROFILERATE:-$DEFAULT_PPROF_MEMPROFILERATE}" \
 --pprof.port "${PPROF_PORT:-$DEFAULT_PPROF_PORT}" \
 --remotedb "${REMOTEDB}" \
 --trace "${TRACE}" \
 --verbosity "${VERBOSITY:-$DEFAULT_VERBOSITY}" \
 --ethstats "${ETHSTATS}" \
 --metrics "${METRICS:-$DEFAULT_METRICS}" \
 --metrics.addr "${METRICS_ADDR}" \
 --metrics.influxdb "${METRICS_INFLUXDB:-$DEFAULT_METRICS_INFLUXDB}" \
 --metrics.influxdb.bucket "${METRICS_INFLUXDB_BUCKET:-$DEFAULT_METRICS_INFLUXDB_BUCKET}" \
 --metrics.influxdb.database "${METRICS_INFLUXDB_DATABASE:-$DEFAULT_METRICS_INFLUXDB_DATABASE}" \
 --metrics.influxdb.endpoint "${METRICS_INFLUXDB_ENDPOINT:-$DEFAULT_METRICS_INFLUXDB_ENDPOINT}" \
 --metrics.influxdb.organization "${METRICS_INFLUXDB_ORGANIZATION:-$DEFAULT_METRICS_INFLUXDB_ORGANIZATION}" \
 --metrics.influxdb.password "${METRICS_INFLUXDB_PASSWORD:-$DEFAULT_METRICS_INFLUXDB_PASSWORD}" \
 --metrics.influxdb.tags "${METRICS_INFLUXDB_TAGS:-$DEFAULT_METRICS_INFLUXDB_TAGS}" \
 --metrics.influxdb.token "${METRICS_INFLUXDB_TOKEN:-$DEFAULT_METRICS_INFLUXDB_TOKEN}" \
 --metrics.influxdb.username "${METRICS_INFLUXDB_USERNAME:-$DEFAULT_METRICS_INFLUXDB_USERNAME}" \
 --metrics.influxdbv2 "${METRICS_INFLUXDBV2:-$DEFAULT_METRICS_INFLUXDBV2}" \
 --metrics.port "${METRICS_PORT:-$DEFAULT_METRICS_PORT}" \
 --miner.extradata "${MINER_EXTRADATA}" \
 --miner.gaslimit "${MINER_GASLIMIT:-$DEFAULT_MINER_GASLIMIT}" \
 --miner.gasprice "${MINER_GASPRICE:-$DEFAULT_MINER_GASPRICE}" \
 --miner.pending.feeRecipient "${MINER_PENDING_FEERECIPIENT}" \
 --miner.recommit "${MINER_RECOMMIT:-$DEFAULT_MINER_RECOMMIT}" \
 --synctarget "${SYNCTARGET}" \
 --version "${VERSION:-false}" \
 --bootnodes "${BOOTNODES}" \
 --discovery.dns "${DISCOVERY_DNS}" \
 --discovery.port "${DISCOVERY_PORT:-$DEFAULT_DISCOVERY_PORT}" \
 --discovery.v4 "${DISCOVERY_V4:-$DEFAULT_DISCOVERY_V4}" \
 --discovery.v5 "${DISCOVERY_V5:-$DEFAULT_DISCOVERY_V5}" \
 --identity "${IDENTITY}" \
 --maxpeers "${MAXPEERS:-$DEFAULT_MAXPEERS}" \
 --maxpendpeers "${MAXPENDPEERS:-$DEFAULT_MAXPENDPEERS}" \
 --nat "${NAT:-$DEFAULT_NAT}" \
 --netrestrict "${NETRESTRICT}" \
 --nodekey "${NODEKEY}" \
 --nodekeyhex "${NODEKEYHEX}" \
 --nodiscover "${NODISCOVER:-$DEFAULT_NODISCOVER}" \
 --port "${PORT:-$DEFAULT_PORT}" \
 --cache "${CACHE:-$DEFAULT_CACHE}" \
 --cache.blocklogs "${CACHE_BLOCKLOGS:-$DEFAULT_CACHE_BLOCKLOGS}" \
 --cache.database "${CACHE_DATABASE:-$DEFAULT_CACHE_DATABASE}" \
 --cache.gc "${CACHE_GC:-$DEFAULT_CACHE_GC}" \
 --cache.noprefetch "${CACHE_NOPREFETCH:-$DEFAULT_CACHE_NOPREFETCH}" \
 --cache.preimages "${CACHE_PREIMAGES:-$DEFAULT_CACHE_PREIMAGES}" \
 --cache.snapshot "${CACHE_SNAPSHOT:-$DEFAULT_CACHE_SNAPSHOT}" \
 --cache.trie "${CACHE_TRIE:-$DEFAULT_CACHE_TRIE}" \
 --crypto.kzg "${CRYPTO_KZG:-$DEFAULT_CRYPTO_KZG}" \
 --fdlimit "${FDLIMIT:-$DEFAULT_FDLIMIT}" \
 --gcmode "${GCMODE:-$DEFAULT_GCMODE}" \
 --history.state "${HISTORY_STATE:-$DEFAULT_HISTORY_STATE}" \
 --history.transactions "${HISTORY_TRANSACTIONS:-$DEFAULT_HISTORY_TRANSACTIONS}" \
 --state.scheme "${STATE_SCHEME}" \
 --syncmode "${SYNCMODE:-$DEFAULT_SYNCMODE}" \
 --blobpool.datacap "${BLOBPOOL_DATACAP:-$DEFAULT_BLOBPOOL_DATACAP}" \
 --blobpool.datadir "${BLOBPOOL_DATADIR:-$DEFAULT_BLOBPOOL_DATADIR}" \
 --blobpool.pricebump "${BLOBPOOL_PRICEBUMP:-$DEFAULT_BLOBPOOL_PRICEBUMP}" \
 --txpool.accountqueue "${TXPOOL_ACCOUNTQUEUE:-$DEFAULT_TXPOOL_ACCOUNTQUEUE}" \
 --txpool.accountslots "${TXPOOL_ACCOUNTSLOTS:-$DEFAULT_TXPOOL_ACCOUNTSLOTS}" \
 --txpool.globalqueue "${TXPOOL_GLOBALQUEUE:-$DEFAULT_TXPOOL_GLOBALQUEUE}" \
 --txpool.globalslots "${TXPOOL_GLOBALSLOTS:-$DEFAULT_TXPOOL_GLOBALSLOTS}" \
 --txpool.journal "${TXPOOL_JOURNAL:-$DEFAULT_TXPOOL_JOURNAL}" \
 --txpool.lifetime "${TXPOOL_LIFETIME:-$DEFAULT_TXPOOL_LIFETIME}" \
 --txpool.locals "${TXPOOL_LOCALS}" \
 --txpool.nolocals "${TXPOOL_NOLOCALS:-$DEFAULT_TXPOOL_NOLOCALS}" \
 --txpool.pricebump "${TXPOOL_PRICEBUMP:-$DEFAULT_TXPOOL_PRICEBUMP}" \
 --txpool.pricelimit "${TXPOOL_PRICELIMIT:-$DEFAULT_TXPOOL_PRICELIMIT}" \
 --txpool.rejournal "${TXPOOL_REJOURNAL:-$DEFAULT_TXPOOL_REJOURNAL}" \
 --vmdebug "${VMDEBUG:-$DEFAULT_VMDEBUG}" \
 --vmtrace "${VMTRACE}" \
 --vmtrace.jsonconfig "${VMTRACE_JSONCONFIG}"
