# Base config for EL + CL + validator 
# dependent variables, non-client options 
# used in options creation 
EXECUTION_CLIENT=erigon
CONSENSUS_CLIENT=lighthouse
EXECUTION_CLIENT_VERSION=2.60.0
CONSENSUS_CLIENT_VERSION=5.1.3

# shared options
# note these options ALWAYS overwrite the client specific options 
BASE_CONFIG_NETWORK=dev
BASE_CONFIG_ENDPOINT_URL=http://localhost:8551
BASE_CONFIG_DATA_DIR=$HOME/nodes/$EXECUTION_CLIENT-$CONSENSUS_CLIENT/$BASE_CONFIG_NETWORK
BASE_CONFIG_SECRETS_FILE=$BASE_CONFIG_DATA_DIR/jwt.hex
BASE_CONFIG_CUSTOM_NETWORK_TESTNET_DIR=$BASE_CONFIG_DATA_DIR/devnet-testnet-data
BASE_CONFIG_CUSTOM_NETWORK_GENESIS_FILE=$BASE_CONFIG_DATA_DIR/devnet-testnet-data/genesis.json 
BASE_CONFIG_CUSTOM_NETWORK_GENESIS_STATE=$BASE_CONFIG_CUSTOM_NETWORK_TESTNET_DIR/genesis.ssz
BASE_CONFIG_VALIDATOR_SHARED_FEE_RECEIPENT_ADDRESS=0x123463a4b065722e99115d6c222f267d9cabb524
BASE_CONFIG_CUSTOM_NETWORK_CHAINCONFIG=$BASE_CONFIG_CUSTOM_NETWORK_TESTNET_DIR/consensus/config.yml
BASE_CONFIG_VALIDATOR_BEACON_RPC_PROVIDER=localhost:4000
BASE_CONFIG_VALIDATOR_NUM_VALIDATORS=64
BASE_CONFIG_VALIDATOR_DATADIR=$BASE_CONFIG_DATA_DIR/validator-data

#FILLED IN BY SCRIPT 
BASE_CONFIG_CUSTOM_NETWORK_BOOTNODES_ENR=
BASE_CONFIG_CUSTOM_NETWORK_NETWORK_ID=

# execution_client only options
# consensus_client only options 
BASE_CONFIG_CL_BEACON_API_URL=
BASE_CONFIG_CL_CHECKPPOINT_SYNC_URL=